### ISSUE TITLE
Migrate to C3 0.6 and d3 5.x

### ISSUE THREAD

**Issue by stof** [keen/keen-dataviz.js#101]
It would be great if a new version of keen-dataviz based on d3 5.x could be released, to allow us to migrate to the new version of d3 in our own code without having to load d3 and C3 twice (which is not good for our users).
The 0.6.0 release of C3 is based on d3 5.x

the 3.x version of d3 is not maintained anymore since quite some time (and yes, I know that C3.js moved away from it only recently)

**Comment by stof** [comment]
List of BC breaks in C3:

- for the version 0.5 migrating to d3 4.x: https://github.com/c3js/c3/pull/2246
- for the version 0.6 migrating to d3 5.x: none (you might be affected by some d3 changes if you use d3 directly)

**Comment by adamkasprowicz** [comment]
Hi @stof 
I've just published updated version of our library, which includes the most recent version of C3/D3.
Thank you

**Comment by stof** [comment]
thanks

**Comment by rahul-winner** [comment]
found one issue in Gauge when I updated C3JS to latest. Here it is https://github.com/c3js/c3/issues/2390
