### ISSUE TITLE
expose d3 and c3

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#115]
for more customisations - expose d3/c3 references, so it'll be possible to run the config code below

```
donut: {
  width: 10,
  label: {
    format: function (value, ratio, id) {
      return d3.format('$')(value);
    }
  }
}
```

**Comment by stof** [comment]
this is now done in https://github.com/keen/keen-dataviz.js/commit/57380fee9e89a6d5211cf485188370d6f35fb611
