### ISSUE TITLE
Legend disappears on second render

### ISSUE THREAD

**Issue by Boorasso** [keen/keen-dataviz.js#116]
Hi there,
I'm pretty new to the whole issue and bug reports so I hope this is the right place for my bug(?) report.
We're using keen-dataviz wrapped up in a React component that allows us to select a date range with a date range picker, submit the query every time the date range is changed by user, and re-render the chart every time new data comes in.
The thing is, the first time data comes in, charts will render just fine, with all the display options being accounted for (in our case legend at the bottom for line charts, legend on the right with a 14 items pagination for pie charts), but if you change the date range, receive new data and call `keen-dataviz.render()` with the new data, the charts will re-render, showing the new data, but legends don't get computed again.
I investigated a little with a console.log() of my keen-dataviz object and found out this : 
First render : 
![capture d ecran 2018-11-09 a 11 21 36](https://user-images.githubusercontent.com/25687174/48257629-4ea8d880-e413-11e8-9696-e0eb0123f5d8.png)

Second render : 
![capture d ecran 2018-11-09 a 11 21 55](https://user-images.githubusercontent.com/25687174/48257645-5b2d3100-e413-11e8-8071-da0a2833cd23.png)

So here's my question : 
Is this a bug on your side that you could fix, or is it me not doing things the right way when making the same keen-dataviz re-render with different data ?

**Comment by adamkasprowicz** [comment]
Hi @Boorasso Thank you for reporting and yes, you're in the right place to do so.
I'll add this bug to our backlog. For now, the simplest solution is to create a new KeenDataviz instance and replace the old one.

**Comment by dariuszlacheta** [comment]
Hi @Boorasso 
The problem with legend disappears on second render was fixed and released today.
