### ISSUE TITLE
KeenDataviz is not defined error

### ISSUE THREAD

**Issue by Spoowy** [keen/keen-dataviz.js#122]
Hey guys,

As of today, I'm getting a JS error when running the demo JSFiddle on the example charts, see here: https://jsfiddle.net/phgbbctp/82/

Cheers,
Erwin

**Comment by adamkasprowicz** [comment]
Hey Erwin!
Thanks for reporting. What's your OS and Browser (+version)?

**Comment by checho221** [comment]
Hey, same issue here, i am using chorme on windows 10

**Comment by checho221** [comment]
@Spoowy  i fixet it by using: https://cdn.jsdelivr.net/npm/keen-dataviz@3.0/dist/keen-dataviz.min.js
@adamkasprowicz please help, i dont want to reset all my services having https://cdn.jsdelivr.net/npm/keen-dataviz@3/dist/keen-dataviz.min.js URL on the code bundle

**Comment by adamkasprowicz** [comment]
@checho221 
I've just cleared jsdelivr cache for this package. Could you confirm if it's working now?

**Comment by checho221** [comment]
@adamkasprowicz yes, it is now working well
