### ISSUE TITLE
area chart combined with metrics

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#127]
Let's add a new chart type like the one below:
![example](https://i.imgur.com/C1u5zZC.png)
"Views Last 24h" from
https://keen.github.io/auto-collector-dashboard/

It contains 3 things:
1. count this_24_hours
2. count this_48_hours - this_24_hours
3. count this_24_hours with interval hourly

**Comment by apryka** [comment]
added in version [3.5.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.5.0)
