### ISSUE TITLE
y axis cuts off some values in line chart

### ISSUE THREAD

**Issue by joannecheng** [keen/keen-dataviz.js#13]
From example page on http://keen.github.io/keen-dataviz.js/:

![screen shot 2016-02-03 at 11 13 43 am](https://cloud.githubusercontent.com/assets/638351/12792263/44a0619a-ca68-11e5-8055-51fc35523cce.png)

I think this is a c3 issue. We could solve this quickly by setting `options.y.axis = { min: 0, padding: { bottom: 0 } }` in the `render` method in `default`, but we'll lose some of the auto scaling that c3 does. Thoughts?

**Comment by dustinlarimer** [comment]
We can calculate the minimum w/ this (console demo):

```javascript
var mins = [];
Keen.utils.each(chart.dataset.selectRow(0), function(col, i){
  if (i > 0) {
    mins.push(chart.dataset.minimum(chart.dataset.selectColumn(i)));
  }
});
console.log( chart.dataset.minimum(mins) );
```

**Comment by dustinlarimer** [comment]
(`.minimum()` takes an array and returns the min value found)

**Comment by dustinlarimer** [comment]
Also, this seems to be a known c3 issue, though it hasn't been addressed directly yet: https://github.com/masayuki0812/c3/issues/1523

**Comment by dustinlarimer** [comment]
This also seems to only occur in stacked `line`, `spline`, `step` charts.

**Comment by dustinlarimer** [comment]
Closing for now, as this should be fixed in a future update to c3.js.
