### ISSUE TITLE
ability to download results

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#133]
Similar functionality to the one from the Explorer's table view.
Add ability to display a "download" button under a chart.
3 download methods:
- [ ] as flattened CSV (eg https://github.com/keen/explorer/blob/99d7c33d990c155cc6fa35802e7ffa07e4fc41a6/lib/js/app/utils/csv.js )
- [ ] as JSON
- [ ] as PNG

Configuration:
```javascript
new KeenDataviz({
  [...] // some other options
  ui: {
    buttons: {
      download: {
        label: 'Download as a CSV file', // optinal - by default it's just "Download"
        type: 'csv',  // optional - by default it's JSON
        position: 'bottom' // optional, to be discussed
      }
    }
  }
})
```

**Comment by apryka** [comment]
released in [v.3.10.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.10.0)
