### ISSUE TITLE
Export SVG D3 visualization to PNG or JPEG

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#134]
add ability to save a chart as a png file. Here's an example:
http://bl.ocks.org/Rokotyan/0556f8facbaf344507cdc45dc3622177

* expose this method for a public use, so people can trigger it manually
* add this function as a download type in #133

**Comment by apryka** [comment]
feature added in [v3.9.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.9.0)
