### ISSUE TITLE
cost reduction: show the execution_metadata is it's available in the response object

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#135]
By default, if the execution_metadata is available in the Result, display a Box that contains that data in an easy-to-read form.

This feature will be used in the development stage of many projects.

Related to:
https://keen.io/docs/api/#execution-metadata
https://keen.io/docs/compute/compute-pricing-guide/

Introduce a new property inside the default config:
```javascript
{
 // ... some other default config options
  ui: {
    // some ui options...
    executionMetadata: true // default
  }
}
```
so people will be able to overwrite it if they want.

**Comment by apryka** [comment]
released in [v.3.11.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.11.0)
