### ISSUE TITLE
add heat map to chart types

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#138]
add D3-based heatmap
eg
http://bl.ocks.org/oyyd/859fafc8122977a3afd6
https://observablehq.com/@d3/d3-calendar-view
https://www.d3-graph-gallery.com/heatmap.html
http://bl.ocks.org/tjdecke/5558084

**Comment by apryka** [comment]
released in https://github.com/keen/keen-dataviz.js/releases/tag/v3.13.0
