### ISSUE TITLE
charts are not being resized

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#142]
how to replicate:
open a window with charts
change size of the window
charts have the same size even when the container's size has changed

solution:
add object.addEventListener("resize", myScript);
after resize happend - run chart.resize();

note: set some timeout to avoid calling resize 1000 times in a second, because resize listener triggers many times eg. https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onresize_addeventlistener

**Comment by apryka** [comment]
fixed in [v.3.5.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.5.0)
