### ISSUE TITLE
Column chart displaying columns from previous render

### ISSUE THREAD

**Issue by formatkaka** [keen/keen-dataviz.js#167]
Hello, I have plotted a `columnchart` visualization of data using `keen-DataViz`. I have applied an `in` filter to a query.

I modify the filter parameter `property_value` based on user input (through HTML dropdown).

Post modification, I make a request for updated data and re-render the graph.
It behaves weird on re-render.

I get graph like image attached. The values `1,2,3,4` on `x-axis` are invalid and columns being shown corresponding to them are from another plot.

The problem happens, when I switch between values in the dropdown. Individually all them render correctly. What might be the issue?

Looks like this is an issue with `columnchart` and `barchart` type. Works perfectly in `table` and `piechart`

![image](https://user-images.githubusercontent.com/11999281/55421220-646f9380-5596-11e9-8328-ccd3ebe6f64e.png)

Regards

**Comment by adamkasprowicz** [comment]
Hi there!
Which version of keen-dataviz do you use to generate this chart?
The easiest solution would be to create a new fresh keenDataviz instance on every property_value change. I'll investigate why the second `render` on the same keenDataviz instance doesn't generate the correct chart.

**Comment by formatkaka** [comment]
Hello,
I am currently using version `3.5.2`. I'll try to share code snippet with you which demonstrates the problem. 

It works fine when I create a new instance, but I guess it would be an antipattern.

Regards

**Comment by adamkasprowicz** [comment]
Hi @formatkaka ,
Please take a look at the example here: https://github.com/keen/keen-dataviz.js#refresh-every-1-minute
I think that the config's property `clearOnRender: true` should fix your issue.
