### ISSUE TITLE
Dataviz will not render area chart if first value is a string; query result values inconsistent

### ISSUE THREAD

**Issue by jaredgalanis** [keen/keen-dataviz.js#184]
We've noticed that in our queries using the keen ruby gem for area charts with no group_by field that sometimes the values returned for queries will return as a string, other times as a number. This is the case even when the query hasn't changed. 

It seems that for an area chart where the first value in the result happens to come back as a string, the dataviz lib won't render the chart properly. We've tested this by manually loading the results into an instance of dataviz and swapping the first value between string and a number confirms this to be an issue.

Note this does not seem to be an issue when group_by is present on a line chart.

Thank so much for taking a look!

**Comment by dariuszlacheta** [comment]
Hello @jaredgalanis,

Can You give me more details about this issue? What Do You mean exactly that chart is not render properly? JSfiddle or similar will be the best to check the code that it is generating this.

**Comment by jaredgalanis** [comment]
Thanks @dariuszlacheta! Here's a JSfiddle that demonstrates the issue:
https://jsfiddle.net/jaredgalanis/Lj5e6nbg/1/
Here is another where I've manually updated the first value to be a number and you can see the chart is rendering the data properly:
https://jsfiddle.net/jaredgalanis/m0nkpwz6/

**Comment by dariuszlacheta** [comment]
Hello @jaredgalanis,

Thank You for jsfiddles, I am working right now on this issue. I will let You now when it will be fixed.
For now You can use this option to be sure that every value is a number:

```javascript
const client = new KeenAnalysis({
  projectId: 'YOUR_PROJECT_ID',
  readKey: 'YOUR_READ_KEY',
  resultParsers: [
    (value) => {
      return Number(value); // 
    }
  ]
});
```

Also You can parse results into Your custom functions when getting results from keen-analysis.js.

**Comment by dariuszlacheta** [comment]
Hello @jaredgalanis,

I just publish new version of keen-analysis.js that should solve Your problem :) Please update version to 3.4.1 in Your project

**Comment by jaredgalanis** [comment]
@dariuszlacheta thank you!

**Comment by jaredgalanis** [comment]
@dariuszlacheta actually one question in follow up. We don't actually use the Keen Analysis JS client, we use the Keen Analysis Ruby gem. Is there a fix that's needed for that client as well?

**Comment by dariuszlacheta** [comment]
@jaredgalanis Unfortunately right now We don't have any ruby developer to help You with this issue with Keen Analysis Ruby gem , but I found another solution for You.

In keen-dataviz.js, before render chart, You can parse result with Your custom function:
https://github.com/keen/keen-dataviz.js/#custom-data-parser

I don't have access to Your data but I believe that this will work for Your results:

```javascript
function customParser(result){
   return result.map(el => {
      return {
         ...el,
         value: !isNaN(Number(el.value)) ? Number(el.value) : el.value,
      }
   })
}
chart.render(customParser(result));
```

**Comment by jaredgalanis** [comment]
@dariuszlacheta, sounds good. Thank you, I have implemented something substantially similar to this and it seems to be working well.
