### ISSUE TITLE
onclick - copy to clipboard

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-dataviz.js#191]
when I click on a point on the chart (like in the example below) I want to automatically copy the result's value into my clipboard.
![](https://i.imgur.com/47ucX8n.png)

Note: this feature will be ON by default, but we can switch it off in the config
```javascript
new KeenDataviz({
// some props

utils: {
  clickToCopyToClipboard: false, 
}
})
```

**Comment by apryka** [comment]
released in [v.3.11.0](https://github.com/keen/keen-dataviz.js/releases/tag/v3.11.0)
