### ISSUE TITLE
.colors() doesnt have effect for .type('metric')

### ISSUE THREAD

**Issue by venil7** [keen/keen-dataviz.js#41]
Calling `.colors([..])` does not seem to have any effect, if the type of chart is `metric`
chose n color does not reflect in generated HTML

```
<div class="keen-dataviz">
   <div class="keen-dataviz-metric" style="width: auto; height: 140px;" title="13632"> 
     <span class="keen-dataviz-metric-value" style="padding-top: 18px;">13.6k</span>
     <span class="keen-dataviz-metric-title">Sent</span>
   </div>
</div>
```
It always defaults to `blue`, which it picks from CSS...

**Comment by venil7** [comment]
correction, `.color()` has no effect on _any_ type of chart

**Comment by dustinlarimer** [comment]
@venil7 that's correct, the metric has so far been controlled via CSS, but we realize this is a bit confusing and will add this back in, as this makes programmatic color assignment pretty difficult. Currently `.colors()` is used to set the color pattern for all C3.js charts: https://github.com/keen/keen-dataviz.js/blob/master/lib/libraries/default.js#L71

**Comment by ruleant** [comment]
@dustinlarimer  Thanks for (re)introducing `.colors()` in `keen-dataviz`. :) Saves a lot of work to do the same thing with custom themes.

**Comment by dustinlarimer** [comment]
No problem @ruleant - thanks for catching this and proposing we add it back!
