### ISSUE TITLE
[Suggestion] don't expose global variables when used as AMD or CommonJS

### ISSUE THREAD

**Issue by stof** [keen/keen-dataviz.js#51]
when loading the library through AMD or CommonJS, globals are not needed. This would avoid the need to call `noConflict` after loading it, as done in https://github.com/keen/explorer/pull/133/files#diff-5a0ec123989e22eb8d91f2ef551dc058R2

**Comment by dustinlarimer** [comment]
@stof the specific issue you referenced has been resolved in `keen-analysis@1.2.1`: https://github.com/keen/keen-analysis.js/blob/v1.2.1/CHANGELOG.md#121-global-namespace-fix-pt2

I'll keep this issue open for this SDK as well, until we have time to address this. Thanks for the note!

**Comment by adamkasprowicz** [comment]
@stof The latest version of the keen-dataviz is built with Webpack (UMDs).

Before the change (in v1.2), we exported global variables listed below:
- Dataviz
- Dataset
- Keen global object with Keen.Dataset, Keen.Dataviz properties

Right now (v2), we are exporting only:
- Keen global object with Keen.Dataset, Keen.Dataviz properties (for backward compatibility reasons).

If you want to turn off this last global export - define
`const __KEEN_NO_COMMON_GLOBAL_OBJECT__ = true;`
before loading the Keen-Dataviz.js library.

    <script>const __KEEN_NO_COMMON_GLOBAL_OBJECT__ = true;</script>
    <script src="//d26b395fwzu5fz.cloudfront.net/keen-dataviz-2.0.2.min.js"></script>
