### ISSUE TITLE
Issue with Chart Labels

### ISSUE THREAD

**Issue by chrisbell08** [keen/keen-dataviz.js#54]
chart labels always being returned in the format dd/mm/yyyy event when the query is last 24 hours you just get the same label 24 times

<img width="542" alt="screen shot 2016-07-13 at 22 50 08" src="https://cloud.githubusercontent.com/assets/8242722/17035285/60470b74-4f7e-11e6-9f5b-8a23fae6c6fc.png">

**Comment by dustinlarimer** [comment]
@chrisbell08 is this rendered with ChartJS? Perhaps this is better handled as a keen-js issue?

**Comment by chrisbell08** [comment]
yeah but i've only used chart.js with Keen so not sure if the other charting libs have the same issue

**Comment by dustinlarimer** [comment]
@chrisbell08 Ah, ok - sorry for the confusion here. The Chart.js module is part of the keen-js project, but this repo (keen-dataviz.js) is one of 3 new standalone modules that are essentially a full version bump ahead. Chart.js isn't part of this new effort, and will likely be dropped in the future, or at least moved into a separate plugin. This project runs on C3.js/D3.js, and is currently powering our Explorer and Dashboard apps.

If you would like to give this (and keen-analysis.js) a try, here's a quick example of how to do exactly that: https://github.com/keen/keen-dataviz.js/tree/master/docs#example-usage

If you would still like to track this issue, feel free to copy this over to the keen-js repo [here](https://github.com/keen/keen-js/issues/new). 

Sorry for the bumpy ride!

**Comment by chrisbell08** [comment]
no problem thats fine. So will chart.js support stay in the keen-js library?

**Comment by dustinlarimer** [comment]
@chrisbell08 doubtful at this point, as Chart.js usage and interest (in keen-js) has been pretty low. However, it wouldn't take much to build a dataviz plugin that could be installed alongside keen-dataviz.js to make it available. In that case, one might even prefer to support Chart.js 2.0 as well ;)
