### ISSUE TITLE
Support customizing the paginating-legend for pie charts

### ISSUE THREAD

**Issue by semiosis** [keen/keen-dataviz.js#61]
Currently the legend on pie charts generated by paginating-legend.js is very inflexible.

It would be real nice if we could customize its position and size, and also change the limit for key truncation.

**Comment by dustinlarimer** [comment]
Thanks for the suggestion @semiosis! We'll keep this in mind for an upcoming sprint of updates and improvements.

**Comment by scottbullard** [comment]
This is a feature enhancement that we're also looking forward to!

**Comment by adamkasprowicz** [comment]
Fixed in
https://github.com/keen/keen-dataviz.js/releases/tag/v3.0.0
Configuration options:
https://github.com/keen/keen-dataviz.js#legend
We've removed all the CSS styling from the JS files, so you can use your own custom CSS.
