### ISSUE TITLE
Can only `yarn install` with `--ignore-engines`

### ISSUE THREAD

**Issue by topher515** [keen/keen-dataviz.js#62]
It looks like you guys have specified a `node-engine` in your `package.json` file of node `4.0.x`...

    "engines": {
        "node": "4.0.x"
    },

However, this isn't actually correct, since this implies that keen dataviz will only work on `x` where `x` is exactly` 4.0.0 <= x  < 4.1.0`. I believe it should probably read `"node": ">=4.0.0"`.

I'm currently using node v7.0.0 with webpack to bundle keen dataviz into my js app and it works just fine—except that I have to install my dependencies with `yarn --ignore-engines`.

**Comment by tbarn** [comment]
Hey @topher515! Thanks for the issue! I apologize for the delay. Most of the team was out for the Thanksgiving holidays. I'll see if I can find out more on this!

**Comment by topher515** [comment]
FYI, I forked your repo, removed the `engine` field and now i can `yarn` install my forked repo no problem. 

See: https://github.com/zoomforth/keen-dataviz.js/commit/ef2372e7d81e826ce8c7dc721ba70e032f23d2b8
