### ISSUE TITLE
createNullList for loop i variable not declared properly

### ISSUE THREAD

**Issue by aroc** [keen/keen-dataviz.js#69]
Missing a `var` declaration here. Throws error if called.

https://github.com/keen/keen-dataviz.js/blob/master/lib/dataset/utils/create-null-list.js#L3

**Comment by aroc** [comment]
PR to fix: https://github.com/keen/keen-dataviz.js/pull/70

**Comment by dustinlarimer** [comment]
Has this been released yet?

**Comment by dustinlarimer** [comment]
Looks like it has been- closing 👍
