### ISSUE TITLE
Gauge initial animation

### ISSUE THREAD

**Issue by joaoamaral** [keen/keen-dataviz.js#77]
It seems the loading animation from the c3.js gauge chart is not working. Is there an optional parameter needed to be passed?

So I made two codepens both with equivalent gauge charts.
The first one has the initial animation and uses the old method (client.draw)
The second one uses the Keen.DataViz but doesn't have the animation

https://codepen.io/joaoamaral/pen/MveOqd
https://codepen.io/joaoamaral/pen/YxWEMx

**Comment by dustinlarimer** [comment]
@joaoamaral sorry for the delayed response here. We've opted to disable the animation feature of C3.js visuals to mitigate the performance impact for charts containing a large number of data points (and dashboards containing more than a few charts). Right now this setting is enforced, but I can understand the case for making this optional. I'll make a note to change this in a future iteration.
