### ISSUE TITLE
Change Chart library

### ISSUE THREAD

**Issue by alejandromagnorsky** [keen/keen-dataviz.js#79]
The default in version 4 is C3.js which are quite ugly (specially the timeline chart). 
Is it possible to use Google Charts? The migration for this module has pretty painful so far.

**Comment by dustinlarimer** [comment]
@alejandromagnorsky the SDK is set up to allow for this, but no work has been planned in this area. For now you can override the C3/D3 stuff by manually creating and rendering a Google Charts visual, and skipping the `.render()` call, like so:

```javascript
var myChart = new Keen.Dataviz()
  .data(queryResponse)
  .el('.my-google-chart')
  .call(function(){
    var data = google.visualization.arrayToDataTable(this.data());
    var options = {
      // Google Charts Options
    };
    var visual = new google.visualization.LineChart(this.el());
    google.visualization.events.addListener(visual, 'error', function(stack){
      myChart.message(getErrorMessage(stack));
    });
    visual.draw(data, options);
  });

function getErrorMessage(stack){
  return errorMapping[stack['message']] || stack['message'] || 'An error occurred';
}
```

Google Charts has been problematic for a lot folks, to say the least, and our intention has been to move away from it entirely. If there's enough interest, we could certainly look into creating a plugin that reinstates this functionality.

**Comment by alejandromagnorsky** [comment]
I'm fine with using a different library to Google Charts. I agree that Google Charts is sometimes painful to configure exactly to one's needs. However, C3 looks horrible to be honest.
Why C3 and not ChartJS? I'm curious about the reason behind the decision.

Thanks.

**Comment by adamkasprowicz** [comment]
Hi @alejandromagnorsky 

There are mainly 3 reasons standing behind this decision

1. the library has to have MIT licence, so people would be able to use it for free
https://en.wikipedia.org/wiki/Comparison_of_JavaScript_charting_libraries
For example - Highcharts are amazing, but not every developer is able to pay 1500$ the licence.

2. the library has to be mature and easy to extend
Charts.js are great, but they lack some functions that our customers are demanding.
They are growing fast and some day we could consider moving from C3, but for now it's too soon.
Chartsjs are <canvas> based - this is why all of their charts looks so smooth and shiny. We prefer using SVGs, to have better interactivity.

3.
D3 is the data visualisation library.
https://github.com/d3/d3/wiki/Gallery
You can do pretty much everything you can imagine, so it was pretty natural to use the biggest d3-based lib - c3.

If you have any other questions - please let me know.
