### ISSUE TITLE
Dist version of the library without C3 included

### ISSUE THREAD

**Issue by stof** [keen/keen-dataviz.js#87]
Currently, the dist files are bundling C3 and D3.

Would it be possible to also provide a version where C3 and D3 are not bundled, to reuse the version I'm using in my project without making the user download it twice ?

**Comment by dustinlarimer** [comment]
@stof thanks for the rec - I've been thinking about doing this as well, but just haven't had time to set up a build config for it. 

If you're using webpack you may be able to swap D3 and C3 for custom files that reference and import global versions of these libraries. I understand the value of a proper dist/release, but perhaps this could unblock you until we can get this addressed?

**Comment by stof** [comment]
Well, I'm not using webpack currently (which is precisely why I have this issue)

**Comment by adamkasprowicz** [comment]
@stof The latest version (2.0.2) of our package solves this issue for you.
Please use .js files from `/dist/external_d3_c3/`

**Comment by stof** [comment]
thanks

**Comment by stof** [comment]
The CSS is missing from this `/dist/external_d3_c3/` to have only the keen-dataviz CSS but not the C3 one (to avoid loading it twice for the same reason)

**Comment by stof** [comment]
and are these JS files available on your CDN too ? And if yes, with which naming ?
