### ISSUE TITLE
Getting SSL warning

### ISSUE THREAD

**Issue by tyrw** [keen/keen-dataviz.js#88]
Chrome is throwing SSL warning for Symantec cert:

`The SSL certificate used to load resources from https://d26b395fwzu5fz.cloudfront.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`

Not sure if this is a Keen IO config or a Cloudfront one, but wanted to get it out there so it doesn't sneak up on your team.

**Comment by dustinlarimer** [comment]
@tyrw this is due to a change happening within AWS/Cloudfront, but Keen has been informed that this will be resolved prior to M70 👍
