### ISSUE TITLE
Labels are being escaped

### ISSUE THREAD

**Issue by alejandromagnorsky** [keen/keen-dataviz.js#89]
I am trying to use a special symbol in a label like: `< 90 days`.
However, it shows as `&lt; 90 days`.

**Comment by dustinlarimer** [comment]
@alejandromagnorsky this is by design, to prevent code injection. Would you propose an alternate design for how label content is rendered?

**Comment by alejandromagnorsky** [comment]
All I am saying is that I tried this in C3 and it displays fine. However, perhaps we can decode the `&lt;` as `<`. That way my label will be `&lt; 90 days` but it will display decoded as `< 90 days`.

**Comment by dustinlarimer** [comment]
Hey, there! I’m no longer with Keen, so I’m afraid this issue will remain
on hold for the time being. I would recommend escalating this through a
support thread or their public Slack community ✌🏻

**Comment by adamkasprowicz** [comment]
@alejandromagnorsky could you provide more information about your issue? I'm having hard time trying to reproduce it.

Please visit:
https://jsfiddle.net/mhxaenw8/5/

Can you see labels with < >?
Could you share some part of js code that you are using to render your chart?

**Comment by alejandromagnorsky** [comment]
@adamkasprowicz , just to confirm, is this going to be fixed? Because to me it is a very intricate bug but still a bug nevertheless. Of course I can bypass it in my code but the current behaviour is not normal.

Thank you.

**Comment by adamkasprowicz** [comment]
Hi @alejandromagnorsky ,
Yes, this bug is going to be fixed in the next realease. Thank you for the details

**Comment by alejandromagnorsky** [comment]
Hello @adamkasprowicz ,

Do you have an ETA for the new release?

Thank you.
Regards.

**Comment by adamkasprowicz** [comment]
Hi @alejandromagnorsky 
Next version of keen-dataviz.js lib will be released on 21st of May.
Regards

**Comment by alejandromagnorsky** [comment]
Hello @adamkasprowicz . I am using the latest version (v4.3.1) of the keen bundle from the CDN:
https://cdnjs.com/libraries/keen-js
Could you update that bundle as well please? as the issue still persist there.

Thank you.

**Comment by adamkasprowicz** [comment]
Hi @alejandromagnorsky !
Yes, I will update keen-js dependencies in the next 2 weeks.
The delay is caused by to the fact, that I'm finishing quite big piece of work related to all our JS packages.
Thank you!
