### ISSUE TITLE
Embed chart not working in Safari

### ISSUE THREAD

**Issue by fieg** [keen/keen-dataviz.js#93]
Hi, I pasted the complete embed code/html for a chart. It works in Chrome, but not in Safari.

Chrome (Version 65.0.3325.181):

![screen shot 2018-03-22 at 12 21 30](https://user-images.githubusercontent.com/1086908/37767846-cf9457fc-2dcb-11e8-8e3f-5e161eb52565.png)

Safari (Version 11.0.3):

![screen shot 2018-03-22 at 12 21 51](https://user-images.githubusercontent.com/1086908/37767855-d8d15946-2dcb-11e8-9ded-b091d64891bb.png)

**Comment by adamkasprowicz** [comment]
Could you run your code on localhost?
It looks like your domain has invalid certificate.
https://discussions.apple.com/thread/7449937

**Comment by fieg** [comment]
I did some more debugging and found an "InvalidAccessError". Looking it up with Google it turned out that my adblocker was causing this.
